AWSTemplateFormatVersion: 2010-09-09
Description: Scenarion 2 Template 1 - S3 Source Code Bucket to upload the packaged python lambda
Resources:
  CS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cs3bucket

  LambdaFunctionResource:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CsLambdaCF
      code:
        S3Bucket: cs3bucket
        S3Key: lambda.zip
      Description: This will be used to run the lambda python code
      Handler: lambda.lambda_handler
      Role: 'arn:aws:iam::123456789012:role/lambda-role'
      Runtime: python3.7
      Timeout: 120

Outputs:
  S3BucketName:
    Description: The S3 bucket name for the code deployment
    Value: !Ref CS3Bucket
