AWSTemplateFormatVersion: 2010-09-09
Description: A template for creating S3 Bucket and use to upload the packaged python lambda source code to
Resources:
  CS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: cs.s3.bucket
      
  LambdaFunctionResource:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: CsLambdaCF
      code:
        S3Bucket: cs.s3.bucket
        S3Key: lambda.zip
      Description: This will be used to run the lambda python code
      Handler: lambda.lambda_handler
      Role: 'arn:aws:iam::123456789012:role/lambda-role'
      Runtime: python3.7
      Timeout: 120

