AWSTemplateFormatVersion: 2010-09-09

Description: ECS Infrastructure Interview Template 1

Parameters:
  pArtifactS3Key:
    Default: S3Artkey
    Description: Name of the Artifact S3 Key
    Type: AWS::S3::S3Artkey::pArtifactS3Key
  pArtifactS3BucketName:
    Description: Name of artifact bucketname
    Type: AWS::S3::cs3bucket::pArtifactS3BucketName
  pLogLevel:
    Description: verbosity level of function loggers
    Type: String
    Default: DEBUG
    AllowedValues:
      - CRITICAL
      - ERROR
      - WARNING
      - INFO
      - DEBUG

Resources:
  rLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Name: lambda-function-role
      Path: /
      Policies:
        - PolicyName: allow-ec2
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - ec2:*
              Effect: Allow
              Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/AmazonGlacierFullAccess

  rLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.lambda_handler
      Environment:
        Variables:
          LOG_LEVEL: !Ref pLogLevel
      CodeUri:
        Bucket: !Ref pArtifactS3BucketName
        Key: !Ref pArtifactS3Key
      Role: !Ref rLambdaFunctionRole
      DeploymentPreference:
        Type: AllAtOnce
      Alarms:
        - !Ref rLambdaFunctionAliasErrorAlarm
        - !Ref rLambdaFunctionVersionErrorAlarm

  pFunctionAliasName:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref rLambdaFunction
      #FunctionVersion: !GetAtt rLambdaFunction.Version 
      #FunctionVersion: !Ref rLambdaFunction.Version
      Name: FunctionAlias
      Description: Task LambdaFunction alias

  rLambdaFunctionAliasErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub ${rLambdaFunction}:${pFunctionAliasName}
        - Name: FunctionName
          Value: !Ref rLambdaFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 300
      Statistic: Sum
      Threshold: 0
    
  rLambdaFunctionVersionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          #Value: !Ref rLambdaFunction.Version
          Value: !GetAtt rLambdaFunction.Version
        - Name: FunctionName
          Value: !Ref rLambdaFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 300
      Statistic: Sum
      Threshold: 0

Outputs:
  LambdaFunctionName:
    Description: The lambda code name for the deployment
    Value: !Ref rLambdaFunction

